[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'junegunn/fzf'
build = './install -all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'junegunn/rainbow_parentheses.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['neoterm']
hook_add = '''
  let g:neoterm_default_mod='belowright'
  let g:neoterm_size=10
  let g:neoterm_autoscroll=1
  let g:neoterm_shell = '$SHELL -l'

  let g:test#strategy = 'neoterm'
  let g:test#preserve_screen = 1
  let g:test#python#runner = 'pytest'
  let g:test#python#pytest#executable = 'python3 -m pytest'
'''
