#!/usr/bin/env bash

if [[ -z "$(cat /tmp/move-space-with-app 2> /dev/null)" ]]; then
  touch /tmp/move-space-with-app
fi


NOW=$(ruby -e 'puts (Time.now.to_f*1000).floor')
if [[ -n "$(cat /tmp/move-space-with-app | grep $1)" ]]; then
  COUNT=$(($(cat /tmp/move-space-with-app | grep $1 | awk -F ',' '{print $3}')+1))
  LAST_SWITCHED=$(cat /tmp/move-space-with-app | grep $1 | awk -F ',' '{print $2}')

  if [[ $NOW -gt $LAST_SWITCHED+1000 ]]; then
    COUNT=0
  fi
else
  COUNT=0
fi
echo "$1,$NOW,$COUNT" > /tmp/move-space-with-app

CURRENT=$(yabai -m query --spaces --space | jq '.index')
IFS=$'\n' read -r -d '' -a SPACES < <( yabai -m query --windows | jq -c '.[] | [.app, .space]' | jq -r 'join(",")' | grep $1 | awk -F ',' '{print $2}' | sort | uniq | sed -e "/^$CURRENT$/d" && printf '\0' )

if [[ -z "${SPACES[@]}" ]]; then
  exit 1
fi

# yabai -m query --windows | jq -c '.[] | [.app, .space]' | jq -r 'join(",")' | grep $1 >&2

LENGTH=$(wc -w <<< "${SPACES[@]}")

SPACE=${SPACES[$(( $COUNT % $LENGTH ))]}

yabai -m space --focus $SPACE
