{
  security.pki.certificates = [
  ''
    -----BEGIN CERTIFICATE-----
    MIIDyjCCArKgAwIBAgIUCjNT1HQnCanEf25DJNsKqIrC6+QwDQYJKoZIhvcNAQEL
    BQAwGzEZMBcGA1UEAxMQbG91dHJlcy5pbnRlcm5hbDAeFw0yNDA2MjUwNjQwNDda
    Fw0zNDA2MjMwNjQxMTdaMBsxGTAXBgNVBAMTEGxvdXRyZXMuaW50ZXJuYWwwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5VrCaw+qHzHjX3m+u9HpkRmNw
    1iDZeYXADjzG+xrOuZGfjrXQqOjEAWEaMsoRWKaG0tH7yIU4u9pMGvEi7uo1YpDq
    7gNJF7jQCpihaTTfCPyiOQHDtvUYm/CNi5mVtya6qIcy0s9OWhjxON3FR2/PtCPH
    L6ZYOc5tj97EVGSzRDdEiQ1nKv0DSeQkEwE/QZXGJIuXeyxndKkqh5c5rhGw8hLi
    a0H9OVnTwQa3BXb/ax5v0Unec8J3fHEuXkqXjg1WXIeTgakXws5PDTqpLAnyv/Xo
    Fyev74LBdKIw7PV73wMuYX0laKUp/nsAfBj4yxrh27q1vsBGiS2UfUsMmYk5AgMB
    AAGjggEEMIIBADAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
    HQ4EFgQUhls/Ef/EBK2oMeFv7zTNfOlkxsMwHwYDVR0jBBgwFoAUhls/Ef/EBK2o
    MeFv7zTNfOlkxsMwRAYIKwYBBQUHAQEEODA2MDQGCCsGAQUFBzAChihodHRwczov
    L3ZhdWx0LmxvdXRyZXMuaW50ZXJuYWwvdjEvcGtpL2NhMBsGA1UdEQQUMBKCEGxv
    dXRyZXMuaW50ZXJuYWwwOgYDVR0fBDMwMTAvoC2gK4YpaHR0cHM6Ly92YXVsdC5s
    b3V0cmVzLmludGVybmFsL3YxL3BraS9jcmwwDQYJKoZIhvcNAQELBQADggEBALW1
    StWnlfqofCWpt6kOFrhiS/JsfEdm1uSNLogUQ/R5y+oh6E3SWr+IqBx6Os8ggcPO
    50OVGc/F19bwS92LkXXHHHIMUJQuCs7bLSnq/2sv4kpyowzEl4+4ZanCmrqRsPsH
    sycnZPmVitylfTPXlPxCBAA5SUDgSnW7zP1IX9E6y8TWazNdjVUq1hP0mDYjE9sA
    yGTD+fKiRFrU4hhM39U/sVfpUDuL/Da5QHfOY+796OBPlEpvJP2n7afs0lbhRvgC
    YEW4Xwak7lhgrQpl5Pk2tb5HjyUysN7LqCnwrpnVC2gQozloHjOeJWnSL2Oc1mB0
    AG3Eqafj2DNl9j+0+WA=
    -----END CERTIFICATE-----
  ''
  ]
}
